server:
  port: 8458
  max-http-header-size: 20480000

spring:
  datasource:
    url: jdbc:mysql://121.37.39.206:3306/gps_monitoring?characterEncoding=utf-8
    username: gps_monitoring
    password: Zrx@20041009
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 200MB
mybatis-plus:
  global-config:
    banner: false
    enable-sql-runner: true
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: DELETE_FLAG
      logic-delete-value: DELETED
      logic-not-delete-value: NOT_DELETE
  mapper-locations: classpath*:com/test/**/mapping/*.xml,com/bstek/**/mapping/*.xml
  type-handlers-package: com.test.common.handler
  pagination:
    type: OFFSET
mqtt:
  address: tcp://121.37.39.206:1883
  username: admin
  password: public
  qos: 1
  clientId: linux_server
  timeout: 10
  keepalive: 20
  async: true
  topic: gps_data_topic/1





